### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by cristianbarbaro** [zenvdeluca/net_healer#14]
Hello, 
I'm trying to execute net healer and I found several errors during execution. 

My configurations:
- In Redis:

```
redis_enabled = on
# Reddis configuration
redis_port = 6379
redis_host = myIP

graphite = on
graphite_host = myIP
graphite_port = 2003
graphite_prefix = fastnetmon
```
- In redis.conf (`/etc/redis/6379.conf`) I have: `bind myIP`.
- In /etc/influxdb/influxdb.conf

```
[[graphite]]
  enabled = true
  database = "graphite"
  bind-address = ":2003"
  protocol = "tcp"
  consistency-level = "one"
  name-separator = "."

  batch-size = 5000 # will flush if this many points get buffered
  batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

    templates = [
    "fastnetmon.hosts.* app.measurement.cidr.direction.function.resource",
    "fastnetmon.networks.* app.measurement.cidr.direction.resource",
    "fastnetmon.total.* app.measurement.direction.resource"
  ]
```
- In morgoth.yaml:

```
engine:
  influxdb:
    host: myIP
    port: 8086
    user: root
    password: root
    database: graphite
    anomaly_measurement: anomaly
    measurement_tag: m
```

So, when I execute `bundle exec scripts/start`, I see follow errors:

```
 24243620     Rufus::Scheduler::EveryJob "5s" {}
  24243620   error:
  24243620     24243620
  24243620     NoMethodError
  24243620     undefined method `[]' for nil:NilClass
  24243620       script/pooler.rb:22:in `block in <main>'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `call'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `call'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `loop'
  24243620       /var/lib/gems/2.1.0/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'

```

and the templates (hosts, network and total) doesn't create in InfluxDB. 

Thanks.
Regards.

**Comment by ollybee** [comment]
I see am getting the same errors.  I think it may be due to the influxdb version? I'm running 0.12.0.

```
{ 8206240 rufus-scheduler intercepted an error:
  8206240   job:
  8206240     Rufus::Scheduler::EveryJob "5s" {}
  8206240   error:
  8206240     8206240
  8206240     NoMethodError
  8206240     undefined method `[]' for nil:NilClass
  8206240       script/pooler.rb:21:in `block in <top (required)>'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `call'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:300:in `block (3 levels) in start_work_thread'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `call'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:303:in `block (2 levels) in start_work_thread'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `loop'
  8206240       /usr/local/share/gems/gems/rufus-scheduler-3.1.3/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
  8206240   tz:
  8206240     ENV['TZ']: 
  8206240     Time.now: 2016-05-15 10:11:38 +0100
  8206240   scheduler:
  8206240     object_id: 10450960
  8206240     opts:
  8206240       {}
  8206240       frequency: 0.3
  8206240       scheduler_lock: #<Rufus::Scheduler::NullLock:0x000000013ee918>
  8206240       trigger_lock: #<Rufus::Scheduler::NullLock:0x000000013ee878>
  8206240     uptime: 5.115155171 (5s115)
  8206240     down?: false
  8206240     threads: 2
  8206240       thread: #<Thread:0x000000013ee828>
  8206240       thread_key: rufus_scheduler_10450960
  8206240       work_threads: 1
  8206240         active: 1
  8206240         vacant: 0
  8206240         max_work_threads: 28
  8206240       mutexes: {}
  8206240     jobs: 1
  8206240       at_jobs: 0
  8206240       in_jobs: 0
  8206240       every_jobs: 1
  8206240       interval_jobs: 0
  8206240       cron_jobs: 0
  8206240     running_jobs: 1
  8206240     work_queue: 0
} 8206240 .
```

**Comment by cristianbarbaro** [comment]
Works fine with new version of FastNetMon.

regards.
