### ISSUE TITLE
Error | Healer::Actions: | uninitialized constant

### ISSUE THREAD

**Issue by sflynn-anet** [zenvdeluca/net_healer#15]
I am getting this error and am not sure exactly why.  It appears that I have everything setup (somewhat) but i'm not able to track this one down.

```
2016-04-29 15:07:59 - NameError - uninitialized constant Healer::Actions:
        /opt/nethealer/routes/ddos.rb:90:in `block (2 levels) in <class:Healer>'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/2.3.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /var/lib/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /var/lib/gems/2.3.0/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
        /var/lib/gems/2.3.0/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
        /var/lib/gems/2.3.0/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
        /var/lib/gems/2.3.0/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
        /var/lib/gems/2.3.0/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```
### Environment Configuration File

```
# cat .env
SSL_KEY_PATH="/opt/nethealer/ssl/nethealer.key"
SSL_CERT_PATH="/opt/nethealer/ssl/nethealer.crt"

NETHEALER_SERVER="${ipaddress}"
NETHEALER_INFLUXDB="${ipaddress}"
NETHEALER_USERNAME="fastnetmon"
NETHEALER_PASSWORD="fastnetmon"

GRAFANA_URL="http://${grafana_host}:3000"

THRESHOLD_EXPIRE="450"
THRESHOLD_WARNING="2"
THREDHOLD_CRITICAL="3"

NOTIFICATION_EMAIL_SMTP="localhost"
NOTIFICATION_EMAIL_FROM="root"
NOTIFICATION_EMAIL_TO="root"
NOTIFICATION_LOCATION="NULL"

#OPTIONAL PLUGINS

#PAGERDUTY_KEY=""
#FLOWDOCK_TOKENS="allow,multiple,flows,separated,by,comma"
```

**Comment by jdomenechg** [comment]
Hi.

I have exactly the same problem when any action is triggered.

Did you find how to fix it?

Regards,

**Comment by sf32738** [comment]
I have not yet, and i've not had a chance to get back to this project as I've been tasked with a higher priority at this time.  Hopefully by the end of June I can get back to this project.

**Comment by jdomenechg** [comment]
The cause of the problem was the relative symlinks from actions-enabled to actions-available. For any reason net healer didn't include the ruby scripts for actions this way. I just copied the files from one directory to another and now it works. Doing an absolute symlink should also work (I didn't test it).

**Comment by zenvdeluca** [comment]
@jdomenechg thanks for writing up here. the idea of using symlinks is to activate only the plugins you need.
similar to web server sites-enabled folder
